const AccountEmpresario = 'Account - Empresario';
const AccountImportador = 'Account - Importador';
const WelcomeEmpresario = 'Bienvenido Empresario!';
const WelcomeImportador = 'Bienvenido Importador!';
const ErrorCamposCrearViaje = 'Por favor, complete todos los campos!';
const ErrorFechaPasada = 'Sellecione una fecha a partir de los proximos 5 días';
const SuccesViajeCreado = 'El Viaje fue creado de manera exitosa!';
const Empresas = [];
const Importadores = [];
const Viajes = [];
const Solicitudes = [];
let requestToAsign;
let OBJ1Selector = {};
let userLogged = null;
let typeOfUser;
let date = new Date();
let todayMonth = String(date.getMonth() + 1);
let todayDay = String(date.getDay() + 5);
let todayYear = String(date.getFullYear());
let currentDate = todayYear + todayMonth + todayDay;
let showQuantity = 1;
