const AccountEmpresario = 'Account - Empresario';
const AccountImportador = 'Account - Importador';
const WelcomeEmpresario = 'Bienvenido Empresario!';
const WelcomeImportador = 'Bienvenido Importador!';
const Empresas = [];
const Importadores = [];
const Viajes = [];
const Solicitudes = [];
let OBJ1Selector = {};
let userLogged = null;
let typeOfUser;